name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Print ENV
      run: env
    
    - name: 'Vale Linter Testing'
      uses: warrenbuckley/Vale-Linter-Action@releases/v1
